:imagesdir: ..
[preface]
== Prolog

=== Die Idee

Moritz sitzt in der Bahn und sieht aus dem Fenster.
Er hat gerade keine Lust, sich mit etwas Sinnvollem zu beschäftigen.
Schlafen geht auch nicht, weil er einfach nicht müde genug ist.
Außerdem ist es im Großraumwagen zu hell und zu laut.
Sein Blick schweift in die Ferne und bleibt an einem seltsamen Gebäude hängen.

[abstract]
«Welchen Zweck hat dieses Gebäude?», denkt er sich.

Einen Moment später ist es durch eine bewaldete Hügelkette verdeckt.
Weil er eh gerade nichts Besseres zu tun hat, nimmt er sein Smartphone in die Hand.
Er will herausfinden, was das für ein Gebäude ist.

[abstract]
«Welchen Begriff soll ich eingeben?», überlegt er.

Kino, Einkaufszentrum, Museum, er hat ja keine Ahnung, wozu dieses seltsame Gebäude verwendet wird.
Die Suche nach “seltsames Gebäude Frankfurt” bringt - wenig überraschend - keine wirklich nützliche Erkenntnis.
Er beschließt, Google Maps zu verwenden, um das Gebäude zu finden.
Im Reiseplan, der im Zug für Reisende verteilt wird, kann er nachlesen, dass er sich gerade irgendwo zwischen Frankfurt und Fulda befindet.
Aber auch das hilft nicht wirklich.
Recht schnell verliert er das Interesse an der Suche.

[abstract]
«Pah, echt umständlich und anstrengend, diese Sucherei im Internet.», ärgert er sich und legt das Smartphone zur Seite.

Völlig vergessen kann Moritz diesen Vorfall nicht.
Es ist ja auch nicht zum ersten Mal, dass er sich während einer längeren Fahrt mit dem Zug oder Auto fragt, welche spannenden Dinge da an ihm vorbeiziehen.

=== Erste Recherche

Eines Abends sitzt er allein in seinem Hotelzimmer.
Da fällt ihm die Geschichte mit dem seltsamen Gebäude wieder ein.
Er schnappt sich sein Tablet und gibt “android app berg kirche poi erkennen”.
 
.Suchergebnis bei Google (2017)
#tbd# Bild

Am Ende von Moritz‘ Recherche ist klar, dass es offensichtlich noch keine App gibt, die sein konkretes Problem löst.
Er bekommt aber den Eindruck, dass es die technischen Möglichkeiten wie GPS und weitere Sensoren im Smartphone und die notwendigen Daten bei Google, Wikipedia oder Facebook gibt, um eine App zu realisieren.
Die Idee zum Reise-Butler ist geboren.

=== Erste Vision

Moritz beschließt, die Idee des Reise-Butlers aufzugreifen und eine erste Vision einer App zu entwickeln.
Dazu stellt er sich folgende Fragen:

. Wer sind die Nutzer für das Produkt?
. Warum sollten sie das Produkt haben wollen?
. Was macht das Produkt einzigartig?
. Welche Fähigkeiten muss das Produkt haben?

Frage 1 ist leicht zu beantworten: Reisende in Zügen, Bussen, Beifahrer im Auto.
Die App ist für jene Reisende, die sich für die vorbeiziehende Welt interessieren.
Was gleichzeitig die Antwort auf Frage 2 ist.
Zur Beantwortung von Frage 3 will er sich Zeit für eine Recherche im Internet und in den App-Stores von Google und Apple nehmen.
Dabei legt er sich gleichzeitig fest, nur auf die beiden Smartphone-Plattformen von Google (Android) und Apple (iOS) zu setzen.
Die Antwort auf Frage 4 ergibt sich aus der ursprünglichen Idee.
Die App muss einen Reisenden in die Lage versetzen, schnell und sicher vorbeiziehende Sehenswürdigkeiten (also Gebäude, Landmarken oder Berggipfel) zu erkennen und ihm Zusatzinformationen aus dem Internet bereitzustellen.
Sie muss leicht zu bedienen und schnell einsatzbereit sein, weil das vorbeiziehende Objekt nicht sehr lange sichtbar ist, besonders bei schnell fahrenden Zügen.
Aus diesem Grund reicht es nicht, Objekte nur durch die Kamera zu identifizieren.
Die App muss Kenntnis über den Verlauf der Reise haben, z.B. Start- und Zielort, Umstiege oder interessante Orte in der Umgebung der Strecke.

[abstract]
«Ich würde so eine App verwenden.», denkt er sich und zeigt sich mit dieser ersten Vision schon recht zufrieden.

Wenn die App jedoch Realität werden soll, muss Moritz daraus ein Projekt machen.
Er muss eine Grundlage schaffen, um Unterstützer zu finden.
Einen Namen für das Projekt hat er aber:
Der Reise-Butler.

=== Entscheidung für `cards+`

Eine Idee ist die eine Sache, ihre Umsetzung eine andere.
Moritz weiß, dass es ein langer Weg ist, aus der Idee des Reise-Butlers ein Produkt zu machen.
Er will es aber probieren.
In den agilen Methoden der Software-Entwicklung sieht er seine Chance.
Scrum begleitet Moritz schon seit vielen Jahren.
Er war Teil eines Scrum-Teams sowohl als Entwickler als auch als Produktverantwortlicher.
Die Wirksamkeit von Scrum als Werkzeug steht für ihn außer Frage, er vertraut der agilen Methode.
Ob Scrum die richtige Wahl ist, hängt nach seiner Erfahrung ganz stark von den Menschen im Projekt ab.
Scrum ist einfach, erfordert aber ein großes Maß an Disziplin.
Für die erfolgreiche Einführung und Durchführung von Scrum benötigt eine Projektorganisation eine ganze Menge Vertrauen der interessierten Parteien.
Innerhalb der Projektorganisation müssen die Rollen richtig besetzt werden.
Jeder Projektmitarbeiter muss seine Möglichkeiten im Rahmen von Scrum kennen, muss in seiner Rolle Grenzen respektieren und Pflichten akzeptieren.

Das Thema Dokumentation bei agiler Software-Entwicklung durfte Moritz schon mehrfach in Scrum-Teams kontrovers diskutieren.
Das Spektrum ist breit.

[abstract]
«Lesbarer Code ist besser als Dokumentation.», sagen die Einen.

[abstract]
«Das Backlog ist genug Dokumentation.», behaupten Andere.

[abstract]
«Funktionierende Software ist wichtiger als umfassende Dokumentation.», ist einer der Werte des agilen Manifests.

Dokumentation muss angemessen sein.
Das bedeutet für Moritz, dass sie gebraucht wird, also Leser hat, und hilfreich, vollständig und korrekt ist.
Vermutlich sogar in dieser Reihenfolge.
Dokumentation als Alibi möchte er verhindern.
Aber in vielen großen Unternehmen wird der Umfang der Dokumentation durch Vorgaben und Richtlinien bestimmt.
Moritz setzt beim Thema Dokumentation auf die Methode `cards+`.
Die Methode kennt er schon.
Er weiß, er kann sie sofort einsetzen, noch bevor es ein Projekt gibt.
Sie wird ihm helfen, seine Dokumentation in einem Wiki inkrementell zu erstellen.

.Die Methode `cards+` auf einen Blick
****
Die Methode `cards+` ist ein agiler Ansatz, um Wissensmanagement in einem Software-Entwicklungsprojekt richtig zu organisieren und zielgerichtet und inkrementell zu dokumentieren.
Mit einer festen Struktur in einem Wiki und Prinzipien und Praktiken der Entwickler bringt `cards+` Effizienz und Qualität in die Erstellung und Pflege einer Produktdokumentation.
****

Das Wiki ist für Moritz ein sehr wichtiges Werkzeug.
Er kann und will jederzeit an den Inhalten arbeiten, auch unterwegs.
Moritz entscheidet sich für Confluence.
Sein Arbeitgeber betreibt eine eigene Installation.
Dort kann er einen eigenen Bereich für die Produktdokumentation des Reise-Butlers einrichten.

.Confluence macht es möglich.
****
Confluence vom australischen Hersteller Atlassian ist ein leistungsfähiges Wiki.
Ein Confluence-Bereich ist sehr gut geeignet für den Aufbau einer Produktdokumentation.
Confluence hat alle Funktionen, die notwendig sind für die Umsetzung der Methode `cards+`.
****

Den Baustein <<Topic>> will Moritz nutzen, um die Vision des Reise-Butlers zu strukturieren.
Wichtige Randbedingungen wie die Beschränkung auf Android und iOS erfasst er mit dem Baustein <<Decision>>.
Ganz wichtig ist ihm ein Glossar.
Er will sich so ganz früh auf eindeutige Begriffe festlegen, die ihm wichtig sind.

=== Domänensprache

Nach der Einrichtung des Bereiches für die Produktdokumentation des Reise-Butlers in Confluence beginnt Moritz mit dem Glossar, einem wichtigen Qualitätsmerkmal von `cards+`.
Moritz fängt mit den of-fensichtlichen Begriffen an.
Beim Reise-Butler geht es um eine Reise.
Klar.
Für jeden Begriff legt er eine Seite im Glossar an.
Als Vorlage nutzt er den Baustein <<Term>>.
Er schreibt sofort mindestens einen Satz dazu.
Um die Beschreibungen kompakt zu halten, verknüpft er die Begriffe miteinander.
Dadurch kann er die einzelnen Beschreibungen auf das Wesentliche beschränken.
Er braucht nicht jeden Begriff, den er erwähnt, immer wieder aufs Neue erklären.
Mit diesem Vorgehen vermeidet er mehrfache Beschreibungen eines Begriffes.
Er bleibt konsistent in seiner Beschreibung.

[abstract]
«Ist der Nutzer der App ein Reisender, Fahrgast oder Passagier?», fragt er sich.

Moritz entscheidet sich für Fahrgast.
Er lässt sich besser vom Begriff Reise unterscheiden, hat einen Bezug zu Fahrplan bzw. Fahrt und ist nach seinem Empfinden nicht so sperrig wie Passagier.

.Seite Fahrgast
====
tbd Bild
====

Die Erklärung besteht gerade mal aus zwei Sätzen.
In diesen zwei Sätzen stecken aber eine ganze Reihe weiterer Begriffe:
Fahrzeug, Verkehrsmittel, Personal, Verkehrsunternehmen.
Beim Schreiben stellt er fest, dass es gar nicht so einfach ist, jeden Begriff prägnant und korrekt zu beschreiben.
Viele Begriffe haben mehr als eine Bedeutung.
Für den Begriff Fahrgast gibt es zwei weitere Begriffe:
Passagier und Reisender.
Moritz will aber eindeutige Begriffe.
Für die Begriffe Passagier und Reisender legt er deshalb keine Seite an.
Stattdessen trägt er die Begriffe zusätzlich zum Hauptbegriff Fahrgast als Stichworte in der Seite ein.

Ein wichtiges Ziel des Glossars ist es, Klarheit in die Begriffe zu bringen.
Das Glossar baut er so auf, dass es für jeden Buchstaben im Alphabet eine eigene Seite gibt.
Die beiden Buchstaben X und Y fasst er zusammen.
Begriffe, die mit einer Ziffer beginnen, fasst er ebenfalls zusammen.
Jeder dieser Übersichtsseiten zeigt eine Liste aller Begriffe, die diesen Anfangsbuchstaben haben.
Damit findet jeder Leser schnell heraus, ob es überhaupt den Begriff im Glossar gibt, den er sucht.

Schnell stellt Moritz fest, dass Confluence bei der Eingabe von Links so gewisse Tücken hat.
Durch _Copy&Paste_ aus der Leseansicht heraus werden Verknüpfungen zu externen Web-Links, um nur ein Problem zu nennen.
Das ist nicht gut.
Zum Abschluss der Bearbeitung einer Seite wirft Moritz darum immer einen kurzen Blick auf die Seiteninformation.
Er prüft, ob alle Links in dieser Seite plausibel sind.

.Seiteninformation Fahrgast
====
tbd Bild
====

Diese kleine Aufmerksamkeit kostet ihn nur wenig Zeit.
Sie hilft aber, die Qualität der Seite zu erhöhen.
Die Startseite des Glossars enthält darum eine schrittweisen Anleitung für das Anlegen neuer Begriffe und weitere wichtige Hinweise für die Pflege der Seiten.
Außerdem bietet die Startseite eine Suche beschränkt auf diesen Bereich. 
Die Aktivitäten im Glossar werden durch die Anzeige der zuletzt geänderten Begriffe sichtbar.

.Startseite für das Glossar
====
tbd Bild
====

Suchen ist bereits Teil unserer Kultur.
Nicht ohne Grund ist «googeln» der Begriff für eine Suche oder Recherche im Internet.
Was liegt also näher, als diese Idee auch im Wiki umzusetzen.
 
.Volltextsuche im Glossar
====
tbd Bild
====

Die Suche nach Stichworten ist wesentlich exakter als die Volltextsuche.
Stichworte lassen sich kombinieren.
So lässt sich schrittweise das Suchergebnisse verfeinern.
 
.Stichwortsuche im Glossar
====
tbd Bild
====

Im Verlauf der weiteren Analyse wird Moritz die Begriffe noch weiter verfeinern, manche sogar in ihrer Bedeutung schärfen.
Er ist überzeugt, dass eindeutige Begriffe wichtig sind.
Sie führen zu einer gemeinsamen Domänensprache.
Konsequent eingesetzt hilft das Glossar, Widersprüche in den Bausteinen der Systembeschreibung zu erkennen.
Das ist gut für die Qualität der Dokumentation.
