# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name
name: build

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on: [push]

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-java
      # https://github.com/actions/cache
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      # https://github.com/gradle/gradle
      - run: chmod +x gradlew
      - run: ./gradlew build
      
      # https://github.com/peaceiris/actions-gh-pages
      - if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages
