[preface]
== Vorwort

Die Software-Industrie ist im Wandel.
Die Herausforderungen durch _Cloud_, _Big Data_ und das Internet der Dinge erfordern eine Agilität und Transparenz bei der Entwicklung von Software.
Im Kern der digitalen Transformation geht es darum, dass Unternehmen und Organisationen ihre vorhandenen Prozesse und Daten digital verfügbar machen.
Die Konsequenz ist, dass alle Unternehmen zu Softwareentwicklern werden.
Die Entwicklung von Software ist nicht mehr beschränkt auf die IT-Branche.
Bei Software wird es künftig häufiger um individuelle Lösungen statt um Produkte gehen.
Geschwindigkeit ist wichtig.
Kosten und Qualität bilden ein Spannungsfeld, in dem sich eine ganze Reihe von Ideen und Konzepte etabliert haben.
Einige davon haben direkten Einfluss auf die Dokumentation. 

****
Clean Code::

#tbd# Praktiken und Prinzipien, Spielregeln

Domain-Driven Design::

#tbd# gemeinsame Sprache, strategisches und taktisches Design

Agilität::

#tbd# Manifest agiler Software-Entwicklung, Vision, Backlog, Story

Docs-as-Code::

#tbd# Asciidoc, Wiki
****

Dokumentation ist ein Thema in *jedem* Entwicklungsprojekt.
Information ist das Ziel, Dokumentation ist der Weg.
Abhängig von der Organisation und vom Entwicklungsprozess gibt es Pflichtenhefte, Studien, Grob- und Fachfeinkonzepte, fachliche und technische Spezifikationen, Richtlinien, Anleitungen, Entscheidungen, Anweisungen, Skizzen, Handbücher, um nur die bekanntesten Dokumenttypen zu nennen.
Sie unterscheiden sich

* im Zeitpunkt der Erstellung.

* in der Lebensdauer.

* in der Zielgruppe.

* in der Art des Inhaltes.

* in der Komplexität.

Dokumentation ist wie die Software ein fixer Bestandteil des Produktes.
Ändert sich die Software, muss auch ein Teil der Dokumentation angepasst werden oder wird ungültig.
In einem agilen Umfeld muss daher die Tätigkeit des Dokumentierens eine Aufgabe für das ganze Team sein.
Genau wie beim Programmieren von Software gibt es beim Dokumentieren den Anspruch, Ergebnisse mit guter Qualität zu produzieren.

Ein im Jahr 2014 gestar­tetes agiles Ent­wick­lungs­pro­jekt hatte das Ziel, das IT-System der Trans­port­leitungen der Deutschen Bahn zu moderni­sieren.
Meine dort gewon­nenen Erkennt­nisse führ­ten zum ersten Ent­wurf von `cards+` als Ansatz für inkre­men­telles Doku­men­tieren.
Die Prinzipien und Praktiken von `cards+` halfen uns damals, Wissen langfristig und in guter Qualität zu erhalten.
Mit »uns« ist dabei die gesamte Projektorganisation und die interessierten Parteien des Auftraggebers gemeint. 

#tbd# `cards+` ist einfach.

#tbd# `cards+` ist praktisch.

Mit `cards+` haben wir die »besseren Karten«.

